set shell := ["bash", "-uc"]

default:
    @just --list

vpn *args:
    bash vpn.sh {{args}}

install *args:
    bash install.sh {{args}}

finalize:
    bash finalize.sh

data *args:
    bash data.sh {{args}}

setup *args:
    bash setup.sh {{args}}

train *args:
    bash train.sh {{args}}

eval *args:
    bash eval.sh {{args}}

xvla *args:
    bash xvla.sh {{args}}

wandb *args:
    bash wandb.sh {{args}}

allinone *args:
    bash allinone.sh {{args}}

save version:
    bash save.sh {{version}}
