name: xvla-stage2-performance-narrow
method: bayes
project: lehome_xvla_sweep_stage2
metric:
  name: train/loss
  goal: minimize
parameters:
  batch_size:
    value: 8
  steps:
    value: 30000
  log_freq:
    value: 100
  policy_optimizer_lr:
    arg_name: policy.optimizer_lr
    distribution: log_uniform_values
    min: 1.3e-5
    max: 2.9e-5
  policy_optimizer_weight_decay:
    arg_name: policy.optimizer_weight_decay
    values: [0.0, 1.0e-4]
  policy_scheduler_warmup_steps:
    arg_name: policy.scheduler_warmup_steps
    values: [1000]
early_terminate:
  type: hyperband
  min_iter: 3
