dataset:
  repo_id: repo_act
  root: Datasets/example/top_long_merged

policy:
  type: act
  device: cuda
  push_to_hub: false

  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]

  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/train/act_top_long_linear_warmup_cosine_30k
job_name: act_linear_warmup_cosine_30k
batch_size: 16
steps: 30000
save_freq: 5000
log_freq: 1000
use_policy_training_preset: false

optimizer:
  type: adamw
  lr: 1.0e-5
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-4
  grad_clip_norm: 10.0

scheduler:
  type: cosine_decay_with_warmup
  num_warmup_steps: 1000
  num_decay_steps: 30000
  peak_lr: 1.0e-5
  decay_lr: 1.0e-6

wandb:
  enable: false
