set shell := ["bash", "-uc"]

default:
    @just --list

vpn *args:
    bash allinone.sh vpn {{args}}

prepare *args:
    bash allinone.sh prepare {{args}}

data *args:
    bash allinone.sh data {{args}}

setup *args:
    bash allinone.sh setup {{args}}

train *args:
    bash train.sh {{args}}

eval *args:
    bash eval.sh {{args}}

xvla *args:
    bash allinone.sh xvla {{args}}

wandb *args:
    bash allinone.sh wandb {{args}}

sweep *args:
    bash allinone.sh sweep {{args}}

save *args:
    bash allinone.sh save {{args}}

versions:
    bash allinone.sh versions
